### PR TITLE
fix: change LF to CRLF symbol in getAllResponseHeaders facade's method

### PR DESCRIPTION
**Pull request by avivasyuta**
Hello.

The documentation [defines](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders) that the getAllResponseHeaders method of XMLHttpRequest should return all the response headers, separated by CRLF. In xhook facade [implements](https://github.com/jpillora/xhook/blob/main/src/misc/headers.js#L15) LF separator instead of CRLF.

It breaks scripts that manually try to parse the header string received from the method getAllResponseHeaders.

**Example**
```javascript
const xhr = new XMLHttpRequest();
xhr.open('GET', 'https://jsonplaceholder.typicode.com/posts/2', true);
xhr.send(null);
xhr.onreadystatechange = () => {
    if (xhr.readyState === 4) {
        const headers = xhr.getAllResponseHeaders()
        const arrayHeaders = headers.split('\r\n')
    }
}
```

**Output**
```
["cache-control:\tmax-age=43200\ncontent-type:\tapplication/json; charset=utf-8\nexpires:\t-1\npragma:\tno-cache\n"]
```

This code will generate an array of headers that has only one element. So I made a PR with changes that fix this issue.
It will be great if you can check it out.

### CODE REVIEW

**Comment by jpillora** [comment]
Can you plz prettier these files using our prettier config

Run npx prettier --check .
Checking formatting...
[warn] src/misc/headers.js
[warn] tests/convert.spec.ts
[warn] tests/modify-headers.spec.ts
[warn] Code style issues found in 3 files. Forgot to run Prettier?
Error: Process completed with exit code 1.

Other than that, looks like a reasonable change :) though I'll leave this one to @TrickyPi to decide

**Comment by jpillora** [comment]
Sorry! @TrickyPi setup CI - hopefully he can help :)

**Comment by avivasyuta** [comment]
@jpillora unfortunately I cannot understand why prettier checks in CI and locally are different. I have such output
```bash
npx prettier --check .         
Checking formatting...
All matched files use Prettier code style!
```

**Comment by TrickyPi** [comment]
I'll take a look.

**Comment by avivasyuta** [comment]
> I'll take a look.

I realized that I had different version of prettier. Tell me please how I can find out what specific problems are in the files.

**Comment by TrickyPi** [comment]
@avivasyuta Could you try to run `npx prettier --write .`?

**Comment by avivasyuta** [comment]
> @avivasyuta Could you try to run `npx prettier --write .`?

done ✅

**Comment by avivasyuta** [comment]
@TrickyPi could you publish new version of lib?

**Comment by TrickyPi** [comment]
I published v1.6.0 to npm. But the github publish failed, maybe I need to publish manually.

**Pull request merged**
