### PR TITLE
ES6 2020 refactor

### PR DESCRIPTION
**Pull request by jpillora**
Hey @morsdyce, do you still use xhook? I finally got around to modernising the codebase. Do you have time to review this change? 

Changes:
* Using ES6 modules
* Restructured code in entry file `main.js` and `misc/` (helper functions/types) and `patch/` (each type being patched)
* Fixed extra progress event bug

Note, the logic should remain exactly the same except for the new `xhr.readyState <= 3` check in the 
`  facade.addEventListener("progress"...` handler.

Your tests were very handy. Found a silly bug I had during the refactor :) Have you ever done cross-browser testing using Github Actions?

### CODE REVIEW

**Comment by morsdyce** [comment]
Yeah, xhook is still the core engine behind mimic.js.org so I'm still heavily invested :)

The tests were written exactly for the purpose of modernizing the code base however I had issues with cross browser download and upload events making a reliable test.
Which is what stopped me from doing a full refactor.

I have done cross browser testing lately via testcafe but not via GitHub actions.
I evaluated GitHub actions when it came out and I feel it's still not ready for prime time.

It is much more difficult to set up right instead of using great ci systems out there which are much easier to use.

I'll try to go over this as soon as I can

**Comment by jpillora** [comment]
https://dev.to/mizchi/run-crossbrowser-e2e-testing-on-github-actions-671 might be promising...

**Comment by jpillora** [comment]
Code is ready I think, @morsdyce you keen to do a final check before we merge?

also we’ll need to publish to npm once we merge, maybe gh action to npm publish would be handy…

thanks @TrickyPi !

**Comment by jpillora** [comment]
Will merge this in the next few days and manually npm publish

While its front of mind, I hope to:

* create a `main` branch and set it as the default branch
* delete `dist/` and other build files from `main` 
* keep `gh-pages` static hosting for direct imports
* set `main`'s `package.json` file version to "0.0.0-git-tag"
* add a GHA workflow which will run on tag, which will
   * modify `package.json` version to the current tag
   * run `npm build`
   * push all files to `gh-pages` AND
   * run `npm publish`
* use GH releases to formally (tag and) release this library

**Comment by TrickyPi** [comment]
I'm looking forward to it.

**Comment by TrickyPi** [comment]
> * create a `main` branch and set it as the default branch
> * delete `dist/` and other build files from `main`
> * keep `gh-pages` static hosting for direct imports
> * set `main`'s `package.json` file version to "0.0.0-git-tag"
> * add a GHA workflow which will run on tag, which will
>   
>   * modify `package.json` version to the current tag
>   * run `npm build`
>   * push all files to `gh-pages` AND
>   * run `npm publish`
>   * use GH releases to formally (tag and) release this library

After merging this pr, i wonder like to finish some tasks above.

**Comment by jpillora** [comment]
Decided to merge this one to `main` (https://github.com/jpillora/xhook/pull/135), keep `gh-pages` as is for now, and then the `1.5.0` release can be done via the steps above :)

**Comment by jpillora** [comment]
Will release these changes with https://github.com/jpillora/xhook/issues/136

**Pull request closed without merging**
