### PR TITLE
remove FormData patching

### PR DESCRIPTION
**Pull request by avivasyuta**
Related to issue #104 

Patching FormData class causes exceptions when you try use native methods like `entries()`, `get()`, `set()` and etc. because they are not implemented.

It seems to me there is no need to patch FormData, so I removed related code.

Maybe I don't know all the details. Therefore, if patching is necessary, please tell us why it is needed.

### CODE REVIEW

**Comment by jpillora** [comment]
Thanks for the PR, was patched many years ago when you could not read the state back out

I think we can indeed remove it. It’ll break legacy code that relies on it being a plain object but maybe that’s okay… 

thoughts @TrickyPi  ?

**Comment by jpillora** [comment]
https://github.com/jpillora/xhook/issues/151 Maybe this is another reason to just remove the patched formdata

**Comment by TrickyPi** [comment]
> Thanks for the PR, was patched many years ago when you could not read the state back out
> 
> I think we can indeed remove it. It’ll break legacy code that relies on it being a plain object but maybe that’s okay…
> 
> thoughts @TrickyPi ?
I think we can remove it, because we always use the data created by the native `FormData` in the patched `xhr` and `fetch` functions.

**Comment by avivasyuta** [comment]
Yes. It should works fine without breaking changes. Could you merge PR?

**Comment by jpillora** [comment]
Merged, thanks @avivasyuta 

@TrickyPi please release when you're ready

**Comment by TrickyPi** [comment]
released v1.5.5

**Pull request merged**
