### PR TITLE
fix(fetch): preserve properties of Request by default

### PR DESCRIPTION
**Pull request by TrickyPi**
related #113

### CODE REVIEW

**Comment by jpillora** [comment]
hey @TrickyPi do you have access to release these with https://github.com/jpillora/xhook/releases/new ? (can also create a new `vX.Y.Z` tag here)

**Comment by TrickyPi** [comment]
yes, i can access this link.

**Comment by jpillora** [comment]
okay cool, feel free to push new versions (following semver) when fixes go in

**Comment by TrickyPi** [comment]
Ok.

**Pull request merged**
