### PR TITLE
Fix issue #110.

### PR DESCRIPTION
**Pull request by pondermatic**
Headers were not being used with fetch().

### CODE REVIEW

**Comment by morsdyce** [comment]
Great catch! I'm curious on why your application uses the Request constructor instead of url, options. Is there a specific reason for this?

I can see there are additional things that need to be addressed here using the same edge case e.g passing request body, credentials etc.

**Comment by pondermatic** [comment]
When I changed my application from this:
```JavaScript
var request = new Request(
	url.toString(),
	{
		headers: {
			"Accept": "application/json",
		}
	}
);

return fetch(request);
```
to this:
```JavaScript
var request = new Request(
	url.toString()
);
var requestInit = {
	headers: new Headers(
		{
			"Accept": "application/json",
		}
	)
};

return fetch(request, requestInit);
```
I didn't think about changing the Request object to a URL string. The first parameter to fetch() can be either.

**Comment by dickeylth** [comment]
I'm wondering when could this be merged? Because I've also encountered circumstances where headers not been sent with fetch.

**Comment by jpillora** [comment]
Once, #136 is working, we'll be able to push changes to the JS (not CS) source and any fixes will be auto-released

**Comment by TrickyPi** [comment]
@pondermatic would you like to change the code to `es6` and then switch the base branch of this pr to `main`?

**Comment by TrickyPi** [comment]
closes via #145

**Pull request closed without merging**
