### PR TITLE
Add support for fetch

### LINKED ISSUE #36: Feature: fetch() Support
Are there any plans for supporting the new fetch API?

### PR DESCRIPTION
**Pull request by morsdyce**
Please note that some of the things possible with XHR are not possible with the fetch API as the request and response objects are immutable. For example, you cannot modify a response after it has returned, you can return a fake response instead.

I have updated the examples in the relevant cases for use with fetch, as well as handling both fetch and XHR requests at once (in some cases the handler will need to detect it is dealing with a fetch request to modify it correctly).

fixes #36

### CODE REVIEW

**Comment by jpillora** [comment]
Awesome! Thanks for the PR, will hopefully have time to take a look at this on the weekend

**Comment by lironess** [comment]
+1, looking forward to merging it

**Comment by BaTbAbYDeV** [comment]
Is there a reason that this hasn't been merged yet?  Anything outstanding?
thx

**Comment by ilyagelman** [comment]
+1 on merging this

**Comment by jpillora** [comment]
Hi @morsdyce, Sorry for the delay on this. I still haven't found any time to get to this. You look like a trustworthy guy so I've given you commit access. Feel free to merge this yourself (and resolve any other issues you have time for). Once these changes have proven stable, I'll bump up XDomain's version of XHook. Cheers!

**Comment by morsdyce** [comment]
Thanks @jpillora, I have my own open source project that uses xhook at it's core, so xhook is important to me. Since the PR I have added additional functionalities such as web worker and react native support.

I'll work on merging these back to xhook although they involve some complications in the build phase that will need to be solved (currently the coffesscript IIFE uses non existent window and must be removed manually).

Regarding versions, how should we do this? Do you want to add me as a collaborator in NPM as well or do you wish to review the changes before releases?

Thanks

**Comment by jpillora** [comment]
Sounds good. I'd like to remove coffeescript and swap to vanilla so if that suits you better than feel free to make the change. RE: Versioning, as long as its a new minor (1.4.x) I'm not fussed. Oyeah, just added you to NPM.

My main concern is not implementing XMLHttpRequest/fetch APIs perfectly and therefore breaking existing libraries (e.g. I'm missing the XMLHttpRequest constants and #55 fixes this). Then again, shouldn't be too much of a problem if issues are resolved quickly.

**Comment by morsdyce** [comment]
Sounds good, I guess I'll first go over the existing PR's and merge whatever I can and then look into switching to vanilla. Might take a bit of time as i'm currently finishing up a major release of my current project and i'll be on vacation in April but I'll try to make at least the first step before that.

**Comment by jpillora** [comment]
Awesome, anything you can do will be helpful :)

**Comment by BaTbAbYDeV** [comment]
@morsdyce - Quick question - I'm using your fetchapi branch of xhook at the moment (many thanks for that!) but I'm finding that if I disable then enable xhook (using the functions) the fetch function is not replaced with the xhook override on enable because you do a check on line 144 "unless typeof WINDOW[FETCH] is "function"" and it always is (if replaced at the beginning)

Before I fix / change / pull request something here I wanted to know if there was a particular reason you were doing the function check again here in the first place? 

Thanks!

**Comment by morsdyce** [comment]
@BaTbAbYDeV I did the check to make sure I don't break browsers who don't support fetch, there might be an issue with disable/enable as I haven't tested that part yet (we should create a test case for it).

Feel free to suggest a fix for this, although I don't currently see where the issue is.
When you disable xhook I restore the original fetch function to the window and when enabling I just simply check again and restore the xhook override.

**Comment by BaTbAbYDeV** [comment]
@morsdyce - Many thanks for the quick response ! .. great - I can see what you were thinking there ..   

The issue is that if you call xhook.enable() and the fetch function exists (native one) then WINDOW[FETCH] will not be set to XHookFetchRequest and calls will still be passed to the native function.. :)

I should get a chance to sort it out today and do a pull request - thanks again!

**Comment by morsdyce** [comment]
The fetch function should be replaced on start time, so calling enable should only be done after you called disable, which in this state we already have a reference for the browser fetch in the NativeFetch variable

**Pull request merged**
